### ISSUE TITLE
Minimum universal react API

### ISSUE THREAD

**Issue by guidsen** [lancetw/react-isomorphic-bundle#9]
Hi, I've been working on https://github.com/guidsen/react-simple-universal that solved the boilerplate involved with universal React Apps.

I'm really curious about your thoughts about this and would love to have some help evolving this repo.

**Comment by lancetw** [comment]
@guidsen Nice job, I think integrate [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) and [react-helmet](https://github.com/nfl/react-helmet) is a good idea for a great universal react boilerplate and serious examples, and you should consider doing some examples with "async actions" instead of counting in the reducer, the real universal react problems we need to solve them.
